/* ENTIDADES FORTES*/

CREATE TABLE SUPPLIERS(

	SupplierID	SERIAL NOT NULL,
	CompanyName	VARCHAR(40) NOT NULL,
	ContactName	VARCHAR(30) NOT NULL,
	ContactTitle	VARCHAR(30) ,
	Address		VARCHAR(60) NOT NULL,
	City		VARCHAR(15) NOT NULL,
	Region		VARCHAR(15) NOT NULL,
	PostalCode	VARCHAR(10) NOT NULL,
	Country		VARCHAR(15) NOT NULL,
	Phone		VARCHAR(24) NOT NULL,
	Fax		VARCHAR(24),
	HomePage	TEXT
);

ALTER TABLE SUPPLIERS
	ADD CONSTRAINT pk_suppliersID PRIMARY KEY (SupplierID);

ALTER TABLE SUPPLIERS
	ADD CONSTRAINT unq_suppliersID UNIQUE (SupplierID);
	
CREATE TABLE REGION(

	RegionID	SERIAL NOT NULL,
	RegionDescription	CHAR(50)
);

ALTER TABLE REGION
	ADD CONSTRAINT pk_regionID PRIMARY KEY (RegionID);

ALTER TABLE REGION
	ADD CONSTRAINT unq_regionID UNIQUE (RegionID);

CREATE TABLE EMPLOYEES(

	EmployeeID	SERIAL NOT NULL,
	LastName	VARCHAR(20) NOT NULL,
	FirstName	VARCHAR(10) NOT NULL,
	Title		VARCHAR(30) NOT NULL,
	TitleOfCourtesy	VARCHAR(25) NOT NULL,
	BirthDate	DATE NOT NULL,
	HireDate	DATE NOT NULL,
	Address		VARCHAR(60) NOT NULL,
	City		VARCHAR(15) NOT NULL,
	Region		VARCHAR(15) NOT NULL,
	PostalCode	VARCHAR(10) NOT NULL,
	Country		VARCHAR(15) NOT NULL,
	HomePhone	VARCHAR(24) NOT NULL,
	Extension	VARCHAR(4) NOT NULL,
	Photo		BYTEA,
	Notes		TEXT,
	ReportsTo	INTEGER NOT NULL,
	PhotoPath	VARCHAR(255) NOT NULL	
);

ALTER TABLE EMPLOYEES
	ADD CONSTRAINT pk_employeeID PRIMARY KEY (EmployeeID);

ALTER TABLE EMPLOYEES
	ADD CONSTRAINT unq_employeeID UNIQUE (EmployeeID);

CREATE TABLE CUSTOMERS(

	CustomerID	CHAR(5) NOT NULL,
	CompanyName	VARCHAR(40) NOT NULL,
	ContactName	VARCHAR(30) NOT NULL,
	ContactTitle	VARCHAR(30) NOT NULL,
	Address		VARCHAR(60) NOT NULL,
	City		VARCHAR(15) NOT NULL,
	Region		VARCHAR(15) NOT NULL,
	PostalCode	VARCHAR(10) NOT NULL,
	Country		VARCHAR(15) NOT NULL,
	Phone		VARCHAR(24) NOT NULL,
	Fax		VARCHAR(24)
);

ALTER TABLE CUSTOMERS
	ADD CONSTRAINT pk_customerID PRIMARY KEY (CustomerID);

ALTER TABLE CUSTOMERS
	ADD CONSTRAINT unq_customerID UNIQUE (CustomerID);

CREATE TABLE SHIPPERS(

	ShipperID	SERIAL NOT NULL,
	CompanyName	VARCHAR(40) NOT NULL,
	Phone		VARCHAR(24) NOT NULL
);

ALTER TABLE SHIPPERS
	ADD CONSTRAINT pk_shippersID PRIMARY KEY (ShipperID);

ALTER TABLE SHIPPERS
	ADD CONSTRAINT unq_shippersID UNIQUE (ShipperID);

CREATE TABLE CUSTOMER_DEMOGRAPHICS(

	CustomerTypeID	CHAR(10) NOT NULL,
	CustomerDesc	TEXT NOT NULL
);

ALTER TABLE CUSTOMER_DEMOGRAPHICS
	ADD CONSTRAINT pk_customertypeID PRIMARY KEY (CustomerTypeID);

ALTER TABLE CUSTOMER_DEMOGRAPHICS
	ADD CONSTRAINT unq_customertypeID UNIQUE (CustomerTypeID);

CREATE TABLE CATEGORIES(

	CategoryID	SERIAL NOT NULL,
	CategoryName	VARCHAR(15) NOT NULL,
	Description	TEXT NOT NULL,
	Picture		BYTEA

);

ALTER TABLE CATEGORIES 
	ADD CONSTRAINT pk_categoriesID PRIMARY KEY (CategoryID);

ALTER TABLE CATEGORIES
	ADD CONSTRAINT unq_categoriesID UNIQUE (CategoryID); 

/* ENTIDADES FRACAS*/

CREATE TABLE PRODUCTS(

	ProductID	SERIAL NOT NULL,
	ProductName	VARCHAR(40) NOT NULL,
	SupplierID	INTEGER NOT NULL,
	CategoryID	INTEGER NOT NULL,
	QuantityPerUnit	VARCHAR(20) NOT NULL,
	UnitPrice	NUMERIC NOT NULL,
	UnitInStock	SMALLINT NOT NULL,
	UnitsOnOrder	SMALLINT NOT NULL,
	ReorderLevel	SMALLINT NOT NULL,
	Discontinued	BIT NOT NULL
);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT pk_productID PRIMARY KEY (ProductID);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT unq_productID UNIQUE (ProductID);

CREATE TABLE ORDER_DETAILS(

	OrderID		SERIAL NOT NULL,
	ProductID	INTEGER NOT NULL,
	UnitPrice	NUMERIC NOT NULL,
	Quantity	SMALLINT NOT NULL,
	Dicount		REAL NOT NULL
);

ALTER TABLE ORDER_DETAILS
	ADD CONSTRAINT pk_orderID PRIMARY KEY (OrderID);

ALTER TABLE ORDER_DETAILS
	ADD CONSTRAINT unq_orderID UNIQUE (OrderID);

ALTER TABLE ORDER_DETAILS
	ADD CONSTRAINT fk_productID FOREIGN KEY (ProductID) REFERENCES products (ProductID) ON DELETE CASCADE;

CREATE TABLE TERRITORIES(

	TerritoryID	VARCHAR(20) NOT NULL,
	TerritoryDescription	CHAR(50) NOT NULL,
	RegionID	INTEGER NOT NULL
);

ALTER TABLE TERRITORIES
	ADD CONSTRAINT pk_territoriesID PRIMARY KEY (TerritoryID);

ALTER TABLE TERRITORIES
	ADD CONSTRAINT unq_territoriesID UNIQUE (TerritoryID);

CREATE TABLE EMPLOYEE_TERRITORIES(

	EmployeeID	SERIAL NOT NULL,
	TerritoryID	VARCHAR(20) NOT NULL
);
ALTER TABLE EMPLOYEE_TERRITORIES
	ADD CONSTRAINT pk_employeeIDTerritories PRIMARY KEY (EmployeeID);

ALTER TABLE EMPLOYEE_TERRITORIES
	ADD CONSTRAINT unq_employeeIDTerritories UNIQUE (EmployeeID);

ALTER TABLE EMPLOYEE_TERRITORIES 
	ADD CONSTRAINT fk_employeeID FOREIGN KEY (EmployeeID) REFERENCES employees (EmployeeID) ON DELETE CASCADE;

ALTER TABLE EMPLOYEE_TERRITORIES 
	ADD CONSTRAINT fk_territoryID FOREIGN KEY (TerritoryID) REFERENCES territories (TerritoryID) ON DELETE CASCADE;

CREATE TABLE ORDERS(

	OrderID		SERIAL NOT NULL,
	CustomerID	CHAR(5) NOT NULL,
	EmployeeID	INTEGER NOT NULL,
	OrderDate	DATE NOT NULL,
	RequireDate	DATE NOT NULL,
	ShippedDate	DATE NOT NULL,
	ShipVia		INTEGER NOT NULL,
	Freight		NUMERIC NOT NULL,
	ShipName	VARCHAR(40) NOT NULL,
	ShipAddress	VARCHAR(60) NOT NULL,
	ShipCity	VARCHAR(15) NOT NULL,
	ShipRegion	VARCHAR(15) NOT NULL,
	ShipPostalCode	VARCHAR(10) NOT NULL,
	ShipCountry	VARCHAR(15) NOT NULL
	
);

ALTER TABLE ORDERS
	ADD CONSTRAINT pk_orderIDOrders PRIMARY KEY (OrderID);

ALTER TABLE ORDERS
	ADD CONSTRAINT unq_orderIDOrders UNIQUE (OrderID);

CREATE TABLE CUSTOMER_CUSTOMER_DEMO(

	CustomerID	CHAR(5) NOT NULL,
	CustomerTypeID	CHAR(10) NOT NULL
);

ALTER TABLE CUSTOMER_CUSTOMER_DEMO
	ADD CONSTRAINT pk_customerdemoID PRIMARY KEY (CustomerID);

ALTER TABLE CUSTOMER_CUSTOMER_DEMO
	ADD CONSTRAINT unq_customerdemoID UNIQUE (CustomerID);

ALTER TABLE CUSTOMER_CUSTOMER_DEMO 
	ADD CONSTRAINT fk_customerdemoID FOREIGN KEY (CustomerID) REFERENCES customers (CustomerID) ON DELETE CASCADE;
	
ALTER TABLE CUSTOMER_CUSTOMER_DEMO 
	ADD CONSTRAINT fk_customertypedemoID FOREIGN KEY (CustomerTypeID) REFERENCES customer_demographics (CustomerTypeID) ON DELETE CASCADE;
	